export type Exercise = {
  id: string;
  name: string;
  muscleGroup: string;
  secondaryMuscles: string[];
  equipmentType: 'Máquina' | 'Barra' | 'Halteres' | 'Livre' | 'Peso do corpo' | 'Cabo/Polia' | 'Kettlebell' | 'Elástico' | 'Smith';
  difficulty: 'Iniciante' | 'Intermediário' | 'Avançado';
  sets: string;
  reps: string;
  rest: string;
  videoUrl: string;
  description: string;
  tips: string[];
  commonErrors: string[];
  safetyTips: string[];
  variations: string[];
};

export const muscleGroups = [
  { id: 'peito', name: 'Peito', icon: 'Chest' },
  { id: 'costas', name: 'Costas', icon: 'Back' },
  { id: 'ombros', name: 'Ombros', icon: 'Shoulders' },
  { id: 'biceps', name: 'Bíceps', icon: 'Biceps' },
  { id: 'triceps', name: 'Tríceps', icon: 'Triceps' },
  { id: 'pernas', name: 'Pernas', icon: 'Legs' },
  { id: 'panturrilha', name: 'Panturrilha', icon: 'Calves' },
  { id: 'abdomen', name: 'Abdômen', icon: 'Abs' },
  { id: 'antebreaco', name: 'Antebraço', icon: 'Forearms' },
  { id: 'trapezio', name: 'Trapézio', icon: 'Traps' },
  { id: 'lombar', name: 'Lombar', icon: 'LowerBack' },
];

const createEx = (id: string, name: string, muscle: string, equip: any, diff: any = 'Iniciante'): Exercise => ({
  id,
  name,
  muscleGroup: muscle,
  secondaryMuscles: [],
  equipmentType: equip,
  difficulty: diff,
  sets: '3 a 4',
  reps: '10 a 12',
  rest: '60s',
  videoUrl: '',
  description: `Exercício técnico focado no desenvolvimento de ${muscle} com ênfase em ${name}.`,
  tips: ['Mantenha a cadência controlada.', 'Foco na contração muscular máxima.', 'Mantenha o core ativado.'],
  commonErrors: ['Uso de impulso (roubo).', 'Amplitude de movimento reduzida.', 'Postura incorreta da coluna.'],
  safetyTips: ['Mantenha a coluna em posição neutra.', 'Não bloqueie as articulações no final do movimento.'],
  variations: ['Variação de pegada', 'Variação de ângulo'],
});

export const exercises: Record<string, Exercise[]> = {
  peito: [
    createEx('supino-reto-barra', 'Supino Reto com Barra', 'Peito', 'Barra', 'Intermediário'),
    createEx('supino-reto-halter', 'Supino Reto com Halteres', 'Peito', 'Halteres', 'Intermediário'),
    createEx('supino-inc-barra', 'Supino Inclinado com Barra', 'Peito', 'Barra', 'Intermediário'),
    createEx('supino-inc-halter', 'Supino Inclinado com Halteres', 'Peito', 'Halteres', 'Intermediário'),
    createEx('supino-dec-barra', 'Supino Declinado com Barra', 'Peito', 'Barra', 'Avançado'),
    createEx('supino-dec-halter', 'Supino Declinado com Halteres', 'Peito', 'Halteres', 'Avançado'),
    createEx('supino-maq', 'Supino na Máquina', 'Peito', 'Máquina', 'Iniciante'),
    createEx('crucifixo-reto', 'Crucifixo Reto com Halteres', 'Peito', 'Halteres', 'Intermediário'),
    createEx('crucifixo-inc', 'Crucifixo Inclinado', 'Peito', 'Halteres', 'Intermediário'),
    createEx('crucifixo-dec', 'Crucifixo Declinado', 'Peito', 'Halteres', 'Avançado'),
    createEx('peck-deck', 'Crucifixo na Máquina (Peck Deck)', 'Peito', 'Máquina', 'Iniciante'),
    createEx('cross-alto', 'Crossover Alto', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('cross-medio', 'Crossover Médio', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('cross-baixo', 'Crossover Baixo', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('flexao-trad', 'Flexão de Braço Tradicional', 'Peito', 'Peso do corpo', 'Iniciante'),
    createEx('flexao-inc', 'Flexão Inclinada', 'Peito', 'Peso do corpo', 'Iniciante'),
    createEx('flexao-dec', 'Flexão Declinada', 'Peito', 'Peso do corpo', 'Intermediário'),
    createEx('flexao-fechada', 'Flexão Fechada', 'Peito', 'Peso do corpo', 'Intermediário'),
    createEx('pullover-halter', 'Pullover com Halter', 'Peito', 'Halteres', 'Intermediário'),
    createEx('pullover-barra', 'Pullover com Barra', 'Peito', 'Barra', 'Avançado'),
    createEx('chest-press', 'Chest Press Máquina', 'Peito', 'Máquina', 'Iniciante'),
    createEx('supino-smith', 'Supino Guiado (Smith)', 'Peito', 'Smith', 'Iniciante'),
    createEx('cross-unilateral', 'Crossover Unilateral', 'Peito', 'Cabo/Polia', 'Avançado'),
    createEx('press-elastico', 'Press com Elástico', 'Peito', 'Elástico', 'Iniciante'),
    createEx('flexao-argolas', 'Flexão em Argolas', 'Peito', 'Livre', 'Avançado'),
    createEx('supino-neutro', 'Supino com Pegada Neutra', 'Peito', 'Halteres', 'Intermediário'),
    createEx('supino-pausa', 'Supino com Pausa', 'Peito', 'Barra', 'Avançado'),
    createEx('fly-cabo-baixo', 'Fly no Cabo Baixo', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('fly-cabo-alto', 'Fly no Cabo Alto', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('press-unilateral', 'Press Unilateral com Halter', 'Peito', 'Halteres', 'Intermediário'),
  ],
  costas: [
    createEx('barra-fixa-pro', 'Barra Fixa Pronada', 'Costas', 'Peso do corpo', 'Avançado'),
    createEx('barra-fixa-sup', 'Barra Fixa Supinada', 'Costas', 'Peso do corpo', 'Intermediário'),
    createEx('barra-fixa-neu', 'Barra Fixa Neutra', 'Costas', 'Peso do corpo', 'Intermediário'),
    createEx('puxada-frontal-ab', 'Puxada Frontal Aberta', 'Costas', 'Máquina', 'Iniciante'),
    createEx('puxada-frontal-fe', 'Puxada Frontal Fechada', 'Costas', 'Máquina', 'Iniciante'),
    createEx('puxada-triangulo', 'Puxada na Frente com Triângulo', 'Costas', 'Máquina', 'Iniciante'),
    createEx('remada-curvada', 'Remada Curvada com Barra', 'Costas', 'Barra', 'Intermediário'),
    createEx('remada-unilateral', 'Remada Unilateral com Halter', 'Costas', 'Halteres', 'Iniciante'),
    createEx('remada-baixa', 'Remada Baixa no Cabo', 'Costas', 'Cabo/Polia', 'Iniciante'),
    createEx('remada-alta-cabo', 'Remada Alta no Cabo', 'Costas', 'Cabo/Polia', 'Iniciante'),
    createEx('remada-cavalinho', 'Remada Cavalinho (T-bar)', 'Costas', 'Barra', 'Intermediário'),
    createEx('remada-maq', 'Remada na Máquina', 'Costas', 'Máquina', 'Iniciante'),
    createEx('pulldown-maq', 'Pulldown na Máquina', 'Costas', 'Máquina', 'Intermediário'),
    createEx('pullover-cabo', 'Pullover no Cabo', 'Costas', 'Cabo/Polia', 'Intermediário'),
    createEx('pullover-halter-costas', 'Pullover com Halter', 'Costas', 'Halteres', 'Intermediário'),
    createEx('pullover-maq', 'Pullover na Máquina', 'Costas', 'Máquina', 'Avançado'),
    createEx('remada-banco-inc', 'Remada no Banco Inclinado', 'Costas', 'Halteres', 'Intermediário'),
    createEx('remada-invertida', 'Remada Invertida', 'Costas', 'Peso do corpo', 'Iniciante'),
    createEx('terra', 'Levantamento Terra', 'Costas', 'Barra', 'Avançado'),
    createEx('terra-romeno', 'Terra Romeno', 'Costas', 'Barra', 'Intermediário'),
    createEx('terra-sumo', 'Terra Sumô', 'Costas', 'Barra', 'Avançado'),
    createEx('good-morning', 'Good Morning', 'Costas', 'Barra', 'Avançado'),
    createEx('hiperextensao', 'Hiperextensão Lombar', 'Costas', 'Peso do corpo', 'Iniciante'),
    createEx('face-pull', 'Face Pull', 'Costas', 'Cabo/Polia', 'Iniciante'),
    createEx('remada-alta-aberta', 'Remada Alta Aberta', 'Costas', 'Barra', 'Intermediário'),
    createEx('remada-alta-fechada', 'Remada Alta Fechada', 'Costas', 'Barra', 'Intermediário'),
    createEx('pulldown-unilateral', 'Pulldown Unilateral', 'Costas', 'Cabo/Polia', 'Intermediário'),
    createEx('barra-aus', 'Barra Australiana', 'Costas', 'Peso do corpo', 'Iniciante'),
    createEx('rack-pull', 'Rack Pull', 'Costas', 'Barra', 'Avançado'),
    createEx('deadlift-parcial', 'Deadlift Parcial', 'Costas', 'Barra', 'Avançado'),
  ],
  pernas: [
    createEx('agachamento-livre', 'Agachamento Livre', 'Pernas', 'Barra', 'Avançado'),
    createEx('agachamento-front', 'Agachamento Frontal', 'Pernas', 'Barra', 'Avançado'),
    createEx('agachamento-sumo', 'Agachamento Sumô', 'Pernas', 'Halteres', 'Intermediário'),
    createEx('agachamento-bulg', 'Agachamento Búlgaro', 'Pernas', 'Halteres', 'Avançado'),
    createEx('agachamento-smith', 'Agachamento no Smith', 'Pernas', 'Smith', 'Iniciante'),
    createEx('leg-45', 'Leg Press 45°', 'Pernas', 'Máquina', 'Intermediário'),
    createEx('leg-horizontal', 'Leg Press Horizontal', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('extensora', 'Cadeira Extensora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('hack-maq', 'Hack Machine', 'Pernas', 'Máquina', 'Intermediário'),
    createEx('passada', 'Passada', 'Pernas', 'Peso do corpo', 'Iniciante'),
    createEx('afundo', 'Afundo', 'Pernas', 'Halteres', 'Iniciante'),
    createEx('step-up', 'Step-up', 'Pernas', 'Peso do corpo', 'Iniciante'),
    createEx('stiff', 'Stiff', 'Pernas', 'Barra', 'Intermediário'),
    createEx('terra-romeno-pernas', 'Terra Romeno', 'Pernas', 'Barra', 'Intermediário'),
    createEx('mesa-flexora', 'Mesa Flexora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('cadeira-flexora', 'Cadeira Flexora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('glute-bridge', 'Glute Bridge', 'Pernas', 'Peso do corpo', 'Iniciante'),
    createEx('hip-thrust', 'Hip Thrust (Elevação Pélvica)', 'Pernas', 'Barra', 'Intermediário'),
    createEx('abducao-maq', 'Abdução de Quadril Máquina', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('aducao-maq', 'Adução de Quadril Máquina', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('elevacao-pelvica-uni', 'Elevação Pélvica Unilateral', 'Pernas', 'Peso do corpo', 'Intermediário'),
    createEx('avanco-andando', 'Avanço Andando', 'Pernas', 'Peso do corpo', 'Intermediário'),
    createEx('avanco-lugar', 'Avanço no Lugar', 'Pernas', 'Halteres', 'Iniciante'),
    createEx('sled-push', 'Sled Push', 'Pernas', 'Livre', 'Avançado'),
    createEx('sled-pull', 'Sled Pull', 'Pernas', 'Livre', 'Avançado'),
    createEx('pistol', 'Pistol Squat', 'Pernas', 'Peso do corpo', 'Avançado'),
    createEx('box-squat', 'Box Squat', 'Pernas', 'Barra', 'Intermediário'),
    createEx('nordic-curl', 'Nordic Curl', 'Pernas', 'Peso do corpo', 'Avançado'),
    createEx('kettlebell-swing', 'Swing com Kettlebell', 'Pernas', 'Kettlebell', 'Intermediário'),
    createEx('cadeira-abdutora', 'Cadeira Abdutora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('cadeira-adutora', 'Cadeira Adutora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('hack-invertido', 'Hack Invertido', 'Pernas', 'Máquina', 'Avançado'),
    createEx('passada-smith', 'Passada no Smith', 'Pernas', 'Smith', 'Intermediário'),
    createEx('step-back-lunge', 'Step-back Lunge', 'Pernas', 'Halteres', 'Iniciante'),
  ],
  ombros: [
    createEx('desenv-barra', 'Desenvolvimento com Barra', 'Ombros', 'Barra', 'Intermediário'),
    createEx('desenv-halter', 'Desenvolvimento com Halteres', 'Ombros', 'Halteres', 'Intermediário'),
    createEx('desenv-maq', 'Desenvolvimento na Máquina', 'Ombros', 'Máquina', 'Iniciante'),
    createEx('arnold-press', 'Arnold Press', 'Ombros', 'Halteres', 'Avançado'),
    createEx('eleva-lateral', 'Elevação Lateral com Halteres', 'Ombros', 'Halteres', 'Iniciante'),
    createEx('eleva-lateral-cabo', 'Elevação Lateral no Cabo', 'Ombros', 'Cabo/Polia', 'Intermediário'),
    createEx('eleva-lateral-maq', 'Elevação Lateral na Máquina', 'Ombros', 'Máquina', 'Iniciante'),
    createEx('eleva-frontal-barra', 'Elevação Frontal com Barra', 'Ombros', 'Barra', 'Iniciante'),
    createEx('eleva-frontal-halter', 'Elevação Frontal com Halteres', 'Ombros', 'Halteres', 'Iniciante'),
    createEx('eleva-frontal-cabo', 'Elevação Frontal no Cabo', 'Ombros', 'Cabo/Polia', 'Intermediário'),
    createEx('remada-alta-barra', 'Remada Alta com Barra', 'Ombros', 'Barra', 'Iniciante'),
    createEx('eleva-post-peck', 'Elevação Posterior no Peck Deck', 'Ombros', 'Máquina', 'Iniciante'),
    createEx('eleva-post-halter', 'Elevação Posterior com Halteres', 'Ombros', 'Halteres', 'Intermediário'),
    createEx('press-militar', 'Press Militar', 'Ombros', 'Barra', 'Avançado'),
    createEx('press-unilateral', 'Press Unilateral', 'Ombros', 'Halteres', 'Intermediário'),
    createEx('y-raise', 'Y-Raise', 'Ombros', 'Halteres', 'Intermediário'),
  ],
  biceps: [
    createEx('rosca-direta-barra', 'Rosca Direta com Barra', 'Bíceps', 'Barra', 'Iniciante'),
    createEx('rosca-direta-halter', 'Rosca Direta com Halteres', 'Bíceps', 'Halteres', 'Iniciante'),
    createEx('rosca-alt', 'Rosca Alternada', 'Bíceps', 'Halteres', 'Iniciante'),
    createEx('rosca-martelo', 'Rosca Martelo', 'Bíceps', 'Halteres', 'Iniciante'),
    createEx('rosca-martelo-cruz', 'Rosca Martelo Cruzada', 'Bíceps', 'Halteres', 'Intermediário'),
    createEx('rosca-scott', 'Rosca Scott', 'Bíceps', 'Barra', 'Intermediário'),
    createEx('rosca-scott-maq', 'Rosca Scott na Máquina', 'Bíceps', 'Máquina', 'Iniciante'),
    createEx('rosca-cabo', 'Rosca no Cabo', 'Bíceps', 'Cabo/Polia', 'Iniciante'),
    createEx('rosca-21', 'Rosca 21', 'Bíceps', 'Barra', 'Intermediário'),
    createEx('rosca-inv', 'Rosca Inversa', 'Bíceps', 'Barra', 'Iniciante'),
    createEx('rosca-banco-inc', 'Rosca no Banco Inclinado', 'Bíceps', 'Halteres', 'Intermediário'),
    createEx('rosca-spider', 'Rosca Spider', 'Bíceps', 'Barra', 'Avançado'),
    createEx('rosca-uni-cabo', 'Rosca Unilateral no Cabo', 'Bíceps', 'Cabo/Polia', 'Intermediário'),
    createEx('rosca-barra-w', 'Rosca com Barra W', 'Bíceps', 'Barra', 'Iniciante'),
    createEx('chin-up', 'Chin-up (Barra Fixa Supinada)', 'Bíceps', 'Peso do corpo', 'Avançado'),
  ],
  triceps: [
    createEx('triceps-testa-barra', 'Tríceps Testa com Barra', 'Tríceps', 'Barra', 'Intermediário'),
    createEx('triceps-testa-halter', 'Tríceps Testa com Halteres', 'Tríceps', 'Halteres', 'Intermediário'),
    createEx('triceps-corda', 'Tríceps Corda', 'Tríceps', 'Cabo/Polia', 'Iniciante'),
    createEx('triceps-pulley', 'Tríceps no Pulley', 'Tríceps', 'Cabo/Polia', 'Iniciante'),
    createEx('triceps-frances', 'Tríceps Francês', 'Tríceps', 'Halteres', 'Intermediário'),
    createEx('mergulho-paralelas', 'Mergulho em Paralelas', 'Tríceps', 'Peso do corpo', 'Avançado'),
    createEx('mergulho-banco', 'Mergulho em Banco', 'Tríceps', 'Peso do corpo', 'Iniciante'),
    createEx('triceps-coice', 'Tríceps Coice', 'Tríceps', 'Halteres', 'Iniciante'),
    createEx('supino-fechado', 'Supino Fechado', 'Tríceps', 'Barra', 'Avançado'),
    createEx('ext-cabeca-cabo', 'Extensão acima da cabeça no Cabo', 'Tríceps', 'Cabo/Polia', 'Intermediário'),
    createEx('triceps-maq', 'Tríceps Máquina', 'Tríceps', 'Máquina', 'Iniciante'),
  ],
  panturrilha: [
    createEx('pantu-pe', 'Elevação em Pé', 'Panturrilha', 'Máquina', 'Iniciante'),
    createEx('pantu-sentado', 'Elevação Sentado', 'Panturrilha', 'Máquina', 'Iniciante'),
    createEx('pantu-leg', 'Panturrilha no Leg Press', 'Panturrilha', 'Máquina', 'Intermediário'),
    createEx('pantu-smith', 'Panturrilha no Smith', 'Panturrilha', 'Smith', 'Iniciante'),
    createEx('pantu-uni', 'Panturrilha Unilateral', 'Panturrilha', 'Peso do corpo', 'Iniciante'),
    createEx('pantu-step', 'Panturrilha no Step', 'Panturrilha', 'Peso do corpo', 'Iniciante'),
  ],
  abdomen: [
    createEx('crunch', 'Abdominal Crunch', 'Abdômen', 'Peso do corpo', 'Iniciante'),
    createEx('abd-maq', 'Abdominal Máquina', 'Abdômen', 'Máquina', 'Iniciante'),
    createEx('abd-cabo', 'Abdominal no Cabo', 'Abdômen', 'Cabo/Polia', 'Intermediário'),
    createEx('eleva-perna-barra', 'Elevação de Pernas na Barra', 'Abdômen', 'Peso do corpo', 'Avançado'),
    createEx('prancha', 'Prancha Isométrica', 'Abdômen', 'Peso do corpo', 'Iniciante'),
    createEx('prancha-lateral', 'Prancha Lateral', 'Abdômen', 'Peso do corpo', 'Intermediário'),
    createEx('ab-wheel', 'Ab Wheel', 'Abdômen', 'Livre', 'Avançado'),
    createEx('russian-twist', 'Russian Twist', 'Abdômen', 'Peso do corpo', 'Iniciante'),
    createEx('mountain-climber', 'Mountain Climber', 'Abdômen', 'Peso do corpo', 'Intermediário'),
    createEx('woodchopper', 'Woodchopper no Cabo', 'Abdômen', 'Cabo/Polia', 'Intermediário'),
  ],
  antebreaco: [
    createEx('rosca-inv-ante', 'Rosca Inversa', 'Antebraço', 'Barra', 'Iniciante'),
    createEx('rosca-punho', 'Rosca Punho', 'Antebraço', 'Barra', 'Iniciante'),
    createEx('rosca-punho-rev', 'Rosca Punho Reversa', 'Antebraço', 'Barra', 'Iniciante'),
    createEx('farmers-walk', 'Farmer’s Walk', 'Antebraço', 'Halteres', 'Intermediário'),
    createEx('wrist-roller', 'Wrist Roller', 'Antebraço', 'Livre', 'Iniciante'),
    createEx('hang-barra', 'Hang na Barra', 'Antebraço', 'Peso do corpo', 'Intermediário'),
  ],
  trapezio: [
    createEx('encolhe-barra', 'Encolhimento com Barra', 'Trapézio', 'Barra', 'Iniciante'),
    createEx('encolhe-halter', 'Encolhimento com Halteres', 'Trapézio', 'Halteres', 'Iniciante'),
    createEx('encolhe-smith', 'Encolhimento no Smith', 'Trapézio', 'Smith', 'Iniciante'),
    createEx('encolhe-cabo', 'Encolhimento no Cabo', 'Trapézio', 'Cabo/Polia', 'Iniciante'),
    createEx('face-pull-trap', 'Face Pull', 'Trapézio', 'Cabo/Polia', 'Intermediário'),
    createEx('high-pull', 'High Pull', 'Trapézio', 'Barra', 'Avançado'),
    createEx('rack-pull-trap', 'Rack Pull', 'Trapézio', 'Barra', 'Avançado'),
    createEx('remada-alta-trap', 'Remada Alta', 'Trapézio', 'Barra', 'Intermediário'),
    createEx('shrug-atras', 'Shrug atrás', 'Trapézio', 'Barra', 'Avançado'),
    createEx('shrug-uni', 'Shrug unilateral', 'Trapézio', 'Halteres', 'Intermediário'),
  ],
  lombar: [
    createEx('hiperext-lombar', 'Hiperextensão', 'Lombar', 'Máquina', 'Iniciante'),
    createEx('terra-lombar', 'Levantamento Terra', 'Lombar', 'Barra', 'Avançado'),
    createEx('good-morning-lombar', 'Good Morning', 'Lombar', 'Barra', 'Avançado'),
    createEx('superman', 'Superman', 'Lombar', 'Peso do corpo', 'Iniciante'),
    createEx('bird-dog', 'Bird Dog', 'Lombar', 'Peso do corpo', 'Iniciante'),
    createEx('reverse-hyper', 'Reverse Hyper', 'Lombar', 'Máquina', 'Avançado'),
    createEx('deadlift-parcial-lombar', 'Deadlift Parcial', 'Lombar', 'Barra', 'Avançado'),
  ]
};

export const weeklyProgress = [
  { day: 'Dom', volume: 1800 },
  { day: 'Seg', volume: 3200 },
  { day: 'Ter', volume: 2500 },
  { day: 'Qua', volume: 3800 },
  { day: 'Qui', volume: 2900 },
  { day: 'Sex', volume: 4100 },
  { day: 'Sáb', volume: 0 },
];

export const dailyWorkout = {
  focus: 'Peito e Tríceps',
  muscleId: 'peito',
  exercises: [
    { name: 'Supino Reto Barra', sets: '4', reps: '10' },
    { name: 'Peck Deck', sets: '3', reps: '12' },
    { name: 'Flexão de Braços', sets: '3', reps: 'Fadiga' },
    { name: 'Tríceps Pulley', sets: '4', reps: '12' },
    { name: 'Mergulho no Banco', sets: '3', reps: '15' },
  ],
};

export const nutritionTips = {
  emagrecimento: {
    category: 'Emagrecimento',
    tips: [
      { title: 'Hidratação é Chave', content: 'Beba pelo menos 2 litros de água por dia. Muitas vezes, a sede é confundida com fome.' },
      { title: 'Priorize Proteínas', content: 'Proteínas aumentam a saciedade e ajudam a manter a massa muscular durante a perda de peso.' },
    ],
  },
  hipertrofia: {
    category: 'Hipertrofia',
    tips: [
      { title: 'Superávit Calórico', content: 'Para construir músculos, você precisa consumir mais calorias do que gasta.' },
    ],
  },
  energia: { category: 'Energia', tips: [] },
  'pre-treino': { category: 'Pré-Treino', tips: [] },
  'pos-treino': { category: 'Pós-Treino', tips: [] },
};

export { placeHolderImages } from './placeholder-images';
