
export type Exercise = {
  id: string;
  name: string;
  muscleGroup: string;
  secondaryMuscles: string[];
  equipmentType: 'Máquina' | 'Barra' | 'Halteres' | 'Livre' | 'Peso do corpo' | 'Cabo/Polia' | 'Kettlebell' | 'Elástico' | 'Smith';
  difficulty: 'Iniciante' | 'Intermediário' | 'Avançado';
  sets: string;
  reps: string;
  rest: string;
  videoUrl: string;
  description: string;
  tips: string[];
  commonErrors: string[];
  safetyTips: string[];
  variations: string[];
};

export const muscleGroups = [
  { id: 'peito', name: 'Peito', icon: 'Chest' },
  { id: 'costas', name: 'Costas', icon: 'Back' },
  { id: 'ombros', name: 'Ombros', icon: 'Shoulders' },
  { id: 'biceps', name: 'Bíceps', icon: 'Biceps' },
  { id: 'triceps', name: 'Tríceps', icon: 'Triceps' },
  { id: 'pernas', name: 'Pernas', icon: 'Legs' },
  { id: 'panturrilha', name: 'Panturrilha', icon: 'Calves' },
  { id: 'abdomen', name: 'Abdômen', icon: 'Abs' },
  { id: 'antebreaco', name: 'Antebraço', icon: 'Forearms' },
  { id: 'trapezio', name: 'Trapézio', icon: 'Traps' },
  { id: 'lombar', name: 'Lombar', icon: 'LowerBack' },
];

const createEx = (id: string, name: string, muscle: string, equip: any, diff: any = 'Iniciante', sec: string[] = []): Exercise => ({
  id,
  name,
  muscleGroup: muscle,
  secondaryMuscles: sec,
  equipmentType: equip,
  difficulty: diff,
  sets: '3 a 4',
  reps: '10 a 12',
  rest: '60s',
  videoUrl: '',
  description: `Exercício técnico focado em ${muscle}. Priorize a cadência e a conexão mente-músculo para máxima ativação das fibras.`,
  tips: ['Mantenha a postura neutra.', 'Controle a fase negativa do movimento.', 'Não use impulso.'],
  commonErrors: ['Carga excessiva sacrificando a técnica.', 'Amplitude de movimento reduzida.', 'Falta de estabilização do core.'],
  safetyTips: ['Mantenha as articulações alinhadas.', 'Respire de forma rítmica.'],
  variations: ['Unilateral', 'Pegada variada', 'Isometria no pico'],
});

export const exercises: Record<string, Exercise[]> = {
  peito: [
    createEx('supino-reto-barra', 'Supino Reto com Barra', 'Peito', 'Barra', 'Intermediário', ['Tríceps', 'Ombros']),
    createEx('supino-reto-halter', 'Supino Reto com Halteres', 'Peito', 'Halteres', 'Intermediário'),
    createEx('supino-inc-barra', 'Supino Inclinado com Barra', 'Peito', 'Barra', 'Intermediário'),
    createEx('supino-inc-halter', 'Supino Inclinado com Halteres', 'Peito', 'Halteres', 'Intermediário'),
    createEx('supino-dec-barra', 'Supino Declinado com Barra', 'Peito', 'Barra', 'Avançado'),
    createEx('supino-dec-halter', 'Supino Declinado com Halteres', 'Peito', 'Halteres', 'Avançado'),
    createEx('supino-maq', 'Supino na Máquina', 'Peito', 'Máquina', 'Iniciante'),
    createEx('crucifixo-reto', 'Crucifixo Reto com Halteres', 'Peito', 'Halteres', 'Intermediário'),
    createEx('crucifixo-inc', 'Crucifixo Inclinado', 'Peito', 'Halteres', 'Intermediário'),
    createEx('crucifixo-dec', 'Crucifixo Declinado', 'Peito', 'Halteres', 'Avançado'),
    createEx('crucifixo-maq', 'Crucifixo na Máquina (Peck Deck)', 'Peito', 'Máquina', 'Iniciante'),
    createEx('crossover-alto', 'Crossover Alto', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('crossover-medio', 'Crossover Médio', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('crossover-baixo', 'Crossover Baixo', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('flexao-trad', 'Flexão de Braço Tradicional', 'Peito', 'Peso do corpo', 'Iniciante'),
    createEx('flexao-inc', 'Flexão Inclinada', 'Peito', 'Peso do corpo', 'Iniciante'),
    createEx('flexao-dec', 'Flexão Declinada', 'Peito', 'Peso do corpo', 'Intermediário'),
    createEx('flexao-fechada', 'Flexão Fechada', 'Peito', 'Peso do corpo', 'Intermediário'),
    createEx('pullover-halter', 'Pullover com Halter', 'Peito', 'Halteres', 'Intermediário'),
    createEx('pullover-barra', 'Pullover com Barra', 'Peito', 'Barra', 'Intermediário'),
    createEx('chest-press-maq', 'Chest Press Máquina', 'Peito', 'Máquina', 'Iniciante'),
    createEx('supino-smith', 'Supino Guiado (Smith)', 'Peito', 'Smith', 'Intermediário'),
    createEx('crossover-unilateral', 'Crossover Unilateral', 'Peito', 'Cabo/Polia', 'Avançado'),
    createEx('flexao-argolas', 'Flexão em Argolas', 'Peito', 'Livre', 'Avançado'),
    createEx('supino-neutro', 'Supino com Pegada Neutra', 'Peito', 'Halteres', 'Intermediário'),
    createEx('supino-pausa', 'Supino com Pausa', 'Peito', 'Barra', 'Avançado'),
    createEx('fly-cabo-baixo', 'Fly no Cabo Baixo', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('fly-cabo-alto', 'Fly no Cabo Alto', 'Peito', 'Cabo/Polia', 'Intermediário'),
    createEx('press-uni-halter', 'Press Unilateral com Halter', 'Peito', 'Halteres', 'Intermediário'),
  ],
  costas: [
    createEx('barra-fixa-pronada', 'Barra Fixa Pronada', 'Costas', 'Peso do corpo', 'Avançado', ['Bíceps']),
    createEx('barra-fixa-supinada', 'Barra Fixa Supinada', 'Costas', 'Peso do corpo', 'Intermediário'),
    createEx('barra-fixa-neutra', 'Barra Fixa Neutra', 'Costas', 'Peso do corpo', 'Intermediário'),
    createEx('puxada-frontal-aberta', 'Puxada Frontal Aberta', 'Costas', 'Máquina', 'Iniciante'),
    createEx('puxada-frontal-fechada', 'Puxada Frontal Fechada', 'Costas', 'Máquina', 'Iniciante'),
    createEx('puxada-triangulo', 'Puxada com Triângulo', 'Costas', 'Máquina', 'Iniciante'),
    createEx('remada-curvada-barra', 'Remada Curvada com Barra', 'Costas', 'Barra', 'Intermediário'),
    createEx('remada-unilateral-halter', 'Remada Unilateral com Halter', 'Costas', 'Halteres', 'Iniciante'),
    createEx('remada-baixa-cabo', 'Remada Baixa no Cabo', 'Costas', 'Cabo/Polia', 'Iniciante'),
    createEx('remada-alta-cabo', 'Remada Alta no Cabo', 'Costas', 'Cabo/Polia', 'Iniciante'),
    createEx('remada-cavalinho', 'Remada Cavalinho (T-bar)', 'Costas', 'Barra', 'Intermediário'),
    createEx('remada-maq', 'Remada na Máquina', 'Costas', 'Máquina', 'Iniciante'),
    createEx('pulldown-maq', 'Pulldown na Máquina', 'Costas', 'Máquina', 'Intermediário'),
    createEx('pullover-cabo', 'Pullover no Cabo', 'Costas', 'Cabo/Polia', 'Intermediário'),
    createEx('pullover-halter-costas', 'Pullover com Halter', 'Costas', 'Halteres', 'Intermediário'),
    createEx('remada-invertida', 'Remada Invertida', 'Costas', 'Peso do corpo', 'Iniciante'),
    createEx('lev-terra', 'Levantamento Terra', 'Costas', 'Barra', 'Avançado', ['Pernas', 'Lombar']),
    createEx('terra-romeno', 'Terra Romeno', 'Costas', 'Barra', 'Avançado'),
    createEx('terra-sumo', 'Terra Sumô', 'Costas', 'Barra', 'Avançado'),
    createEx('good-morning-costas', 'Good Morning', 'Costas', 'Barra', 'Avançado'),
    createEx('hiperextensao-lombar', 'Hiperextensão Lombar', 'Costas', 'Máquina', 'Iniciante'),
    createEx('face-pull-costas', 'Face Pull', 'Costas', 'Cabo/Polia', 'Iniciante'),
    createEx('remada-alta-aberta', 'Remada Alta Aberta', 'Costas', 'Barra', 'Intermediário'),
    createEx('remada-alta-fechada', 'Remada Alta Fechada', 'Costas', 'Barra', 'Intermediário'),
    createEx('pulldown-uni', 'Pulldown Unilateral', 'Costas', 'Cabo/Polia', 'Intermediário'),
    createEx('barra-australiana', 'Barra Australiana', 'Costas', 'Peso do corpo', 'Iniciante'),
    createEx('puxada-nuca', 'Puxada atrás da nuca (Restrito)', 'Costas', 'Máquina', 'Intermediário'),
    createEx('remada-baixa-pronada', 'Remada Baixa Pegada Pronada', 'Costas', 'Cabo/Polia', 'Intermediário'),
    createEx('remada-baixa-supinada', 'Remada Baixa Pegada Supinada', 'Costas', 'Cabo/Polia', 'Intermediário'),
    createEx('rack-pull', 'Rack Pull', 'Costas', 'Barra', 'Avançado'),
  ],
  ombros: [
    createEx('desenv-barra', 'Desenvolvimento com Barra', 'Ombros', 'Barra', 'Intermediário', ['Tríceps']),
    createEx('desenv-halter', 'Desenvolvimento com Halteres', 'Ombros', 'Halteres', 'Iniciante'),
    createEx('desenv-maq', 'Desenvolvimento na Máquina', 'Ombros', 'Máquina', 'Iniciante'),
    createEx('arnold-press', 'Arnold Press', 'Ombros', 'Halteres', 'Avançado'),
    createEx('eleva-lateral-halter', 'Elevação Lateral com Halteres', 'Ombros', 'Halteres', 'Iniciante'),
    createEx('eleva-lateral-cabo', 'Elevação Lateral no Cabo', 'Ombros', 'Cabo/Polia', 'Intermediário'),
    createEx('eleva-lateral-maq', 'Elevação Lateral na Máquina', 'Ombros', 'Máquina', 'Iniciante'),
    createEx('eleva-frontal-barra', 'Elevação Frontal com Barra', 'Ombros', 'Barra', 'Iniciante'),
    createEx('eleva-frontal-halter', 'Elevação Frontal com Halteres', 'Ombros', 'Halteres', 'Iniciante'),
    createEx('eleva-frontal-cabo', 'Elevação Frontal no Cabo', 'Ombros', 'Cabo/Polia', 'Intermediário'),
    createEx('remada-alta-ombro', 'Remada Alta com Barra', 'Ombros', 'Barra', 'Intermediário'),
    createEx('eleva-post-peck', 'Elevação Posterior no Peck Deck', 'Ombros', 'Máquina', 'Iniciante'),
    createEx('eleva-post-halter', 'Elevação Posterior com Halteres', 'Ombros', 'Halteres', 'Intermediário'),
    createEx('face-pull-ombro', 'Face Pull', 'Ombros', 'Cabo/Polia', 'Iniciante'),
    createEx('press-militar', 'Press Militar', 'Ombros', 'Barra', 'Avançado'),
    createEx('press-unilateral', 'Press Unilateral', 'Ombros', 'Halteres', 'Intermediário'),
    createEx('eleva-lat-inc', 'Elevação Lateral Inclinada', 'Ombros', 'Halteres', 'Avançado'),
    createEx('eleva-lat-sent', 'Elevação Lateral Sentada', 'Ombros', 'Halteres', 'Intermediário'),
    createEx('eleva-front-anilha', 'Elevação Frontal com Anilha', 'Ombros', 'Livre', 'Iniciante'),
    createEx('y-raise', 'Y-raise', 'Ombros', 'Halteres', 'Avançado'),
  ],
  biceps: [
    createEx('rosca-direta-barra', 'Rosca Direta com Barra', 'Bíceps', 'Barra', 'Iniciante'),
    createEx('rosca-direta-halter', 'Rosca Direta com Halteres', 'Bíceps', 'Halteres', 'Iniciante'),
    createEx('rosca-alternada', 'Rosca Alternada', 'Bíceps', 'Halteres', 'Iniciante'),
    createEx('rosca-martelo', 'Rosca Martelo', 'Bíceps', 'Halteres', 'Iniciante'),
    createEx('rosca-martelo-cruzada', 'Rosca Martelo Cruzada', 'Bíceps', 'Halteres', 'Intermediário'),
    createEx('rosca-concentrada', 'Rosca Concentrada', 'Bíceps', 'Halteres', 'Iniciante'),
    createEx('rosca-scott-barra', 'Rosca Scott com Barra', 'Bíceps', 'Barra', 'Intermediário'),
    createEx('rosca-scott-maq', 'Rosca Scott na Máquina', 'Bíceps', 'Máquina', 'Iniciante'),
    createEx('rosca-cabo', 'Rosca no Cabo', 'Bíceps', 'Cabo/Polia', 'Iniciante'),
    createEx('rosca-21', 'Rosca 21', 'Bíceps', 'Barra', 'Avançado'),
    createEx('rosca-inversa', 'Rosca Inversa', 'Bíceps', 'Barra', 'Intermediário', ['Antebraço']),
    createEx('rosca-banco-inc', 'Rosca no Banco Inclinado', 'Bíceps', 'Halteres', 'Intermediário'),
    createEx('rosca-spider', 'Rosca Spider', 'Bíceps', 'Barra', 'Avançado'),
    createEx('chin-up', 'Chin-up (Barra Fixa Supinada)', 'Bíceps', 'Peso do corpo', 'Intermediário'),
    createEx('rosca-uni-cabo', 'Rosca Unilateral no Cabo', 'Bíceps', 'Cabo/Polia', 'Intermediário'),
    createEx('rosca-barra-w', 'Rosca com Barra W', 'Bíceps', 'Barra', 'Iniciante'),
    createEx('rosca-isometrica', 'Rosca Isométrica', 'Bíceps', 'Halteres', 'Avançado'),
    createEx('rosca-45-graus', 'Rosca em 45 graus', 'Bíceps', 'Halteres', 'Intermediário'),
  ],
  triceps: [
    createEx('triceps-testa-barra', 'Tríceps Testa com Barra', 'Tríceps', 'Barra', 'Intermediário'),
    createEx('triceps-testa-halter', 'Tríceps Testa com Halteres', 'Tríceps', 'Halteres', 'Intermediário'),
    createEx('triceps-corda', 'Tríceps Corda', 'Tríceps', 'Cabo/Polia', 'Iniciante'),
    createEx('triceps-pulley', 'Tríceps no Pulley', 'Tríceps', 'Cabo/Polia', 'Iniciante'),
    createEx('triceps-frances', 'Tríceps Francês', 'Tríceps', 'Halteres', 'Intermediário'),
    createEx('triceps-frances-uni', 'Tríceps Francês Unilateral', 'Tríceps', 'Halteres', 'Intermediário'),
    createEx('mergulho-paralelas', 'Mergulho em Paralelas', 'Tríceps', 'Peso do corpo', 'Avançado'),
    createEx('mergulho-banco', 'Mergulho em Banco', 'Tríceps', 'Peso do corpo', 'Iniciante'),
    createEx('triceps-coice', 'Tríceps Coice', 'Tríceps', 'Halteres', 'Iniciante'),
    createEx('supino-fechado', 'Supino Fechado', 'Tríceps', 'Barra', 'Intermediário'),
    createEx('ext-acima-halter', 'Extensão acima da cabeça com halter', 'Tríceps', 'Halteres', 'Intermediário'),
    createEx('ext-acima-cabo', 'Extensão acima da cabeça no cabo', 'Tríceps', 'Cabo/Polia', 'Intermediário'),
    createEx('triceps-maq', 'Tríceps Máquina', 'Tríceps', 'Máquina', 'Iniciante'),
    createEx('triceps-barra-v', 'Tríceps com Barra V', 'Tríceps', 'Cabo/Polia', 'Iniciante'),
    createEx('triceps-reversa', 'Tríceps com Pegada Reversa', 'Tríceps', 'Cabo/Polia', 'Intermediário'),
  ],
  pernas: [
    createEx('agachamento-livre', 'Agachamento Livre', 'Pernas', 'Barra', 'Avançado', ['Glúteos']),
    createEx('agachamento-frontal', 'Agachamento Frontal', 'Pernas', 'Barra', 'Avançado'),
    createEx('agachamento-sumo', 'Agachamento Sumô', 'Pernas', 'Barra', 'Intermediário'),
    createEx('agachamento-bulgaro', 'Agachamento Búlgaro', 'Pernas', 'Halteres', 'Avançado'),
    createEx('agachamento-smith', 'Agachamento no Smith', 'Pernas', 'Smith', 'Intermediário'),
    createEx('leg-press-45', 'Leg Press 45°', 'Pernas', 'Máquina', 'Intermediário'),
    createEx('leg-press-horiz', 'Leg Press Horizontal', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('cadeira-extensora', 'Cadeira Extensora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('hack-machine', 'Hack Machine', 'Pernas', 'Máquina', 'Intermediário'),
    createEx('passada', 'Passada', 'Pernas', 'Peso do corpo', 'Intermediário'),
    createEx('afundo', 'Afundo', 'Pernas', 'Halteres', 'Iniciante'),
    createEx('stiff', 'Stiff', 'Pernas', 'Barra', 'Intermediário'),
    createEx('terra-romeno-perna', 'Terra Romeno', 'Pernas', 'Barra', 'Avançado'),
    createEx('mesa-flexora', 'Mesa Flexora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('cadeira-flexora', 'Cadeira Flexora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('hip-thrust', 'Hip Thrust (Elevação Pélvica)', 'Pernas', 'Barra', 'Intermediário', ['Glúteos']),
    createEx('glute-bridge', 'Glute Bridge', 'Pernas', 'Peso do corpo', 'Iniciante'),
    createEx('cadeira-abdutora', 'Cadeira Abdutora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('cadeira-adutora', 'Cadeira Adutora', 'Pernas', 'Máquina', 'Iniciante'),
    createEx('pistol-squat', 'Pistol Squat', 'Pernas', 'Peso do corpo', 'Avançado'),
    createEx('box-squat', 'Box Squat', 'Pernas', 'Barra', 'Intermediário'),
    createEx('sled-push', 'Sled Push', 'Pernas', 'Livre', 'Avançado'),
    createEx('nordic-curl', 'Nordic Curl', 'Pernas', 'Peso do corpo', 'Avançado'),
    createEx('deadlift-sumo', 'Deadlift Sumô', 'Pernas', 'Barra', 'Avançado'),
    createEx('hack-invertido', 'Hack Invertido', 'Pernas', 'Máquina', 'Avançado'),
    createEx('passada-smith', 'Passada no Smith', 'Pernas', 'Smith', 'Intermediário'),
  ],
  panturrilha: [
    createEx('eleva-pe', 'Elevação em Pé', 'Panturrilha', 'Máquina', 'Iniciante'),
    createEx('eleva-sentado', 'Elevação Sentado', 'Panturrilha', 'Máquina', 'Iniciante'),
    createEx('panturrilha-leg', 'Panturrilha no Leg Press', 'Panturrilha', 'Máquina', 'Iniciante'),
    createEx('panturrilha-smith', 'Panturrilha no Smith', 'Panturrilha', 'Smith', 'Intermediário'),
    createEx('panturrilha-uni', 'Panturrilha Unilateral', 'Panturrilha', 'Peso do corpo', 'Iniciante'),
    createEx('panturrilha-step', 'Panturrilha no Step', 'Panturrilha', 'Peso do corpo', 'Iniciante'),
    createEx('panturrilha-hack', 'Panturrilha no Hack', 'Panturrilha', 'Máquina', 'Intermediário'),
  ],
  trapezio: [
    createEx('encolhe-barra', 'Encolhimento com Barra', 'Trapézio', 'Barra', 'Iniciante'),
    createEx('encolhe-halter', 'Encolhimento com Halteres', 'Trapézio', 'Halteres', 'Iniciante'),
    createEx('encolhe-smith', 'Encolhimento no Smith', 'Trapézio', 'Smith', 'Iniciante'),
    createEx('encolhe-cabo', 'Encolhimento no Cabo', 'Trapézio', 'Cabo/Polia', 'Iniciante'),
    createEx('face-pull-trap', 'Face Pull', 'Trapézio', 'Cabo/Polia', 'Iniciante'),
    createEx('high-pull', 'High Pull', 'Trapézio', 'Barra', 'Avançado'),
    createEx('rack-pull-trap', 'Rack Pull', 'Trapézio', 'Barra', 'Avançado'),
    createEx('remada-alta-trap', 'Remada Alta', 'Trapézio', 'Barra', 'Intermediário'),
    createEx('shrug-atras', 'Shrug atrás (Smith)', 'Trapézio', 'Smith', 'Avançado'),
    createEx('shrug-uni', 'Shrug Unilateral', 'Trapézio', 'Halteres', 'Intermediário'),
    createEx('encolhe-banco-inc', 'Encolhimento no Banco Inclinado', 'Trapézio', 'Halteres', 'Intermediário'),
    createEx('farmers-walk-trap', 'Farmer’s Walk (Foco Trapézio)', 'Trapézio', 'Halteres', 'Intermediário'),
  ],
  lombar: [
    createEx('hiperextensao-lombar-v2', 'Hiperextensão Lombar', 'Lombar', 'Máquina', 'Iniciante'),
    createEx('lev-terra-lombar', 'Levantamento Terra (Foco Lombar)', 'Lombar', 'Barra', 'Avançado'),
    createEx('good-morning-lombar', 'Good Morning', 'Lombar', 'Barra', 'Avançado'),
    createEx('superman', 'Superman', 'Lombar', 'Peso do corpo', 'Iniciante'),
    createEx('bird-dog', 'Bird Dog', 'Lombar', 'Peso do corpo', 'Iniciante'),
    createEx('reverse-hyper-lombar', 'Reverse Hyper', 'Lombar', 'Máquina', 'Avançado'),
    createEx('deadlift-parcial', 'Deadlift Parcial', 'Lombar', 'Barra', 'Avançado'),
  ],
  abdomen: [
    createEx('crunch', 'Abdominal Crunch', 'Abdômen', 'Peso do corpo', 'Iniciante'),
    createEx('abd-maq', 'Abdominal Máquina', 'Abdômen', 'Máquina', 'Iniciante'),
    createEx('abd-cabo', 'Abdominal no Cabo', 'Abdômen', 'Cabo/Polia', 'Iniciante'),
    createEx('elev-pernas-barra', 'Elevação de Pernas na Barra', 'Abdômen', 'Peso do corpo', 'Avançado'),
    createEx('prancha', 'Prancha Isométrica', 'Abdômen', 'Peso do corpo', 'Iniciante'),
    createEx('ab-wheel', 'Ab Wheel (Roda)', 'Abdômen', 'Livre', 'Avançado'),
    createEx('russian-twist', 'Russian Twist', 'Abdômen', 'Livre', 'Intermediário'),
    createEx('sit-up', 'Sit-up', 'Abdômen', 'Peso do corpo', 'Iniciante'),
    createEx('mountain-climber', 'Mountain Climber', 'Abdômen', 'Peso do corpo', 'Intermediário'),
    createEx('woodchopper', 'Woodchopper no Cabo', 'Abdômen', 'Cabo/Polia', 'Intermediário'),
  ],
  antebreaco: [
    createEx('rosca-inversa-ante', 'Rosca Inversa', 'Antebraço', 'Barra', 'Iniciante'),
    createEx('rosca-punho', 'Rosca Punho', 'Antebraço', 'Barra', 'Iniciante'),
    createEx('rosca-punho-rev', 'Rosca Punho Reversa', 'Antebraço', 'Barra', 'Iniciante'),
    createEx('farmer-walk', 'Farmer’s Walk', 'Antebraço', 'Halteres', 'Intermediário'),
    createEx('wrist-roller', 'Wrist Roller', 'Antebraço', 'Livre', 'Intermediário'),
    createEx('hang-barra', 'Hang na Barra', 'Antebraço', 'Peso do corpo', 'Intermediário'),
  ],
};

export const nutritionTips = {
  emagrecimento: {
    category: 'Emagrecimento',
    tips: [
      { title: 'Déficit Calórico', content: 'Consuma menos calorias do que você gasta diariamente. Priorize alimentos com alta densidade nutricional e poucas calorias.' },
      { title: 'Hidratação', content: 'Beba pelo menos 35ml de água por quilo de peso corporal. A água auxilia no metabolismo da gordura.' },
      { title: 'Proteína', content: 'Mantenha a ingestão de proteína alta para preservar a massa muscular durante a perda de peso.' },
      { title: 'Fibras', content: 'Aumente o consumo de vegetais e grãos integrais para aumentar a saciedade.' },
      { title: 'Consistência', content: 'Resultados duradouros vêm de hábitos sustentáveis, não de dietas restritivas passageiras.' },
    ],
  },
  hipertrofia: {
    category: 'Hipertrofia',
    tips: [
      { title: 'Superávit Calórico', content: 'Coma um pouco mais do que seu corpo gasta para fornecer energia para a construção muscular.' },
      { title: 'Proteína por Kg', content: 'Consuma entre 1.6g a 2.2g de proteína por quilo de peso para otimizar a síntese proteica.' },
      { title: 'Descanso Muscular', content: 'O músculo cresce no descanso. Durma pelo menos 7 a 8 horas por noite.' },
      { title: 'Carboidratos', content: 'Não tenha medo deles; são a principal fonte de combustível para treinos intensos.' },
      { title: 'Progressão de Carga', content: 'Tente aumentar o peso ou as repetições gradualmente ao longo das semanas.' },
    ],
  },
  energia: { 
    category: 'Energia', 
    tips: [
      { title: 'Carboidratos Complexos', content: 'Aveia, batata doce e arroz integral fornecem energia de liberação lenta.' },
      { title: 'Magnésio', content: 'Ajuda na produção de energia e na recuperação muscular.' },
      { title: 'Evite Picos de Açúcar', content: 'Açúcares simples causam picos seguidos de quedas bruscas de energia.' },
    ] 
  },
  'pre-treino': { 
    category: 'Pré-Treino', 
    tips: [
      { title: 'Tempo da Refeição', content: 'Coma carboidratos de fácil digestão 1 a 2 horas antes do treino.' },
      { title: 'Cafeína', content: 'Pode ser uma excelente aliada para aumentar o foco e a performance.' },
      { title: 'Hidratação Prévia', content: 'Não chegue desidratado ao treino; isso reduz sua força significativamente.' },
    ] 
  },
  'pos-treino': { 
    category: 'Pós-Treino', 
    tips: [
      { title: 'Janela Anabólica', content: 'Embora não seja imediata, priorize uma refeição com proteína e carboidrato logo após o treino.' },
      { title: 'Reposição de Glicogênio', content: 'Carboidratos após o treino ajudam a repor a energia perdida e auxiliam na recuperação.' },
      { title: 'Antioxidantes', content: 'Frutas vermelhas ajudam a combater o estresse oxidativo do exercício.' },
    ] 
  },
};

export { placeHolderImages } from './placeholder-images';
