
export type Exercise = {
  id: string;
  name: string;
  muscleGroup: string;
  secondaryMuscles: string[];
  equipmentType: 'Máquina' | 'Barra' | 'Halteres' | 'Livre' | 'Peso do corpo' | 'Cabo/Polia' | 'Kettlebell' | 'Elástico' | 'Smith' | 'Outros';
  movement: 'Empurrar' | 'Puxar' | 'Agachar' | 'Hinge' | 'Core' | 'Isolar';
  difficulty: 'Iniciante' | 'Intermediário' | 'Avançado';
  executionInstructions: string;
  description: string;
  tips: string[];
  commonErrors: string[];
  safetyTips: string[];
  variations: string[];
  tags: string[];
  gifPrincipalUrl: string;
  gifVariationUrl: string;
  gifErrorUrl: string;
  thumbnailUrl: string;
  defaultTrainerNotes: string;
  sets: string;
  reps: string;
  rest: string;
  contraindications?: string;
};

export const muscleGroups = [
  { id: 'peito', name: 'Peito', icon: 'Chest' },
  { id: 'costas', name: 'Costas', icon: 'Back' },
  { id: 'ombros', name: 'Ombros', icon: 'Shoulders' },
  { id: 'biceps', name: 'Bíceps', icon: 'Biceps' },
  { id: 'triceps', name: 'Tríceps', icon: 'Triceps' },
  { id: 'pernas', name: 'Pernas', icon: 'Legs' },
  { id: 'panturrilha', name: 'Panturrilha', icon: 'Calves' },
  { id: 'trapezio', name: 'Trapézio', icon: 'Traps' },
  { id: 'abdomen', name: 'Abdômen', icon: 'Abs' },
  { id: 'antebreaco', name: 'Antebraço', icon: 'Forearms' },
  { id: 'lombar', name: 'Lombar', icon: 'LowerBack' },
];

const createEx = (
  id: string, 
  name: string, 
  muscle: string, 
  equip: Exercise['equipmentType'], 
  move: Exercise['movement'],
  diff: Exercise['difficulty'] = 'Iniciante', 
  sec: string[] = []
): Exercise => ({
  id,
  name,
  muscleGroup: muscle,
  secondaryMuscles: sec,
  equipmentType: equip,
  movement: move,
  difficulty: diff,
  executionInstructions: `1. Posicione-se corretamente no equipamento ${equip}.\n2. Mantenha o core contraído e a postura alinhada.\n3. Execute o movimento de ${move.toLowerCase()} de forma controlada.\n4. Sinta a contração no ${muscle} e retorne lentamente.`,
  description: `Exercício fundamental de ${move.toLowerCase()} para o desenvolvimento de ${muscle}.`,
  tips: ['Mantenha a cadência 2-0-2.', 'Foco na conexão mente-músculo.', 'Respire durante a fase concêntrica.'],
  commonErrors: ['Uso de carga excessiva.', 'Amplitude incompleta.', 'Falta de estabilidade no tronco.'],
  safetyTips: ['Verifique se as travas estão seguras.', 'Use cinturão se necessário.'],
  variations: ['Unilateral', 'Com pausa', 'Drop-set'],
  tags: [muscle.toLowerCase(), move.toLowerCase(), equip.toLowerCase()],
  gifPrincipalUrl: '',
  gifVariationUrl: '',
  gifErrorUrl: '',
  thumbnailUrl: '',
  defaultTrainerNotes: 'Focar na técnica antes de progredir carga.',
  sets: '4',
  reps: '12',
  rest: '60s'
});

export const exercises: Record<string, Exercise[]> = {
  peito: [
    createEx('supino-reto-barra', 'Supino Reto com Barra', 'Peito', 'Barra', 'Empurrar', 'Intermediário', ['Tríceps', 'Ombro Frontal']),
    createEx('supino-reto-halter', 'Supino Reto com Halteres', 'Peito', 'Halteres', 'Empurrar', 'Intermediário'),
    createEx('supino-inc-barra', 'Supino Inclinado com Barra', 'Peito', 'Barra', 'Empurrar', 'Intermediário'),
    createEx('supino-inc-halter', 'Supino Inclinado com Halteres', 'Peito', 'Halteres', 'Empurrar', 'Intermediário'),
    createEx('supino-dec-barra', 'Supino Declinado com Barra', 'Peito', 'Barra', 'Empurrar', 'Avançado'),
    createEx('supino-dec-halter', 'Supino Declinado com Halteres', 'Peito', 'Halteres', 'Empurrar', 'Avançado'),
    createEx('supino-maq', 'Supino na Máquina', 'Peito', 'Máquina', 'Empurrar', 'Iniciante'),
    createEx('crucifixo-reto', 'Crucifixo Reto com Halteres', 'Peito', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('crucifixo-inc', 'Crucifixo Inclinado', 'Peito', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('crucifixo-dec', 'Crucifixo Declinado', 'Peito', 'Halteres', 'Isolar', 'Avançado'),
    createEx('crucifixo-maq', 'Crucifixo na Máquina (Peck Deck)', 'Peito', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('crossover-alto', 'Crossover Alto', 'Peito', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('crossover-medio', 'Crossover Médio', 'Peito', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('crossover-baixo', 'Crossover Baixo', 'Peito', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('flexao-trad', 'Flexão de Braço Tradicional', 'Peito', 'Peso do corpo', 'Empurrar', 'Iniciante'),
    createEx('flexao-inc', 'Flexão Inclinada', 'Peito', 'Peso do corpo', 'Empurrar', 'Iniciante'),
    createEx('flexao-dec', 'Flexão Declinada', 'Peito', 'Peso do corpo', 'Empurrar', 'Intermediário'),
    createEx('flexao-fechada', 'Flexão Fechada', 'Peito', 'Peso do corpo', 'Empurrar', 'Intermediário'),
    createEx('pullover-halter', 'Pullover com Halter', 'Peito', 'Halteres', 'Puxar', 'Intermediário'),
    createEx('pullover-barra', 'Pullover com Barra', 'Peito', 'Barra', 'Puxar', 'Intermediário'),
    createEx('chest-press-maq', 'Chest Press Máquina', 'Peito', 'Máquina', 'Empurrar', 'Iniciante'),
    createEx('supino-smith', 'Supino Guiado (Smith)', 'Peito', 'Smith', 'Empurrar', 'Intermediário'),
    createEx('crossover-unilateral', 'Crossover Unilateral', 'Peito', 'Cabo/Polia', 'Isolar', 'Avançado'),
    createEx('press-elastico', 'Press com Elástico', 'Peito', 'Elástico', 'Empurrar', 'Iniciante'),
    createEx('flexao-argolas', 'Flexão em Argolas', 'Peito', 'Livre', 'Empurrar', 'Avançado'),
    createEx('supino-neutro', 'Supino com Pegada Neutra', 'Peito', 'Halteres', 'Empurrar', 'Intermediário'),
    createEx('supino-pausa', 'Supino com Pausa', 'Peito', 'Barra', 'Empurrar', 'Avançado'),
    createEx('fly-cabo-baixo', 'Fly no Cabo Baixo', 'Peito', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('fly-cabo-alto', 'Fly no Cabo Alto', 'Peito', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('press-uni-halter', 'Press Unilateral com Halter', 'Peito', 'Halteres', 'Empurrar', 'Intermediário'),
  ],
  costas: [
    createEx('barra-fixa-pronada', 'Barra Fixa Pronada', 'Costas', 'Peso do corpo', 'Puxar', 'Avançado', ['Bíceps']),
    createEx('barra-fixa-supinada', 'Barra Fixa Supinada', 'Costas', 'Peso do corpo', 'Puxar', 'Intermediário'),
    createEx('barra-fixa-neutra', 'Barra Fixa Neutra', 'Costas', 'Peso do corpo', 'Puxar', 'Intermediário'),
    createEx('puxada-frontal-aberta', 'Puxada Frontal Aberta', 'Costas', 'Máquina', 'Puxar', 'Iniciante'),
    createEx('puxada-frontal-fechada', 'Puxada Frontal Fechada', 'Costas', 'Máquina', 'Puxar', 'Iniciante'),
    createEx('puxada-triangulo', 'Puxada com Triângulo', 'Costas', 'Máquina', 'Puxar', 'Iniciante'),
    createEx('remada-curvada-barra', 'Remada Curvada com Barra', 'Costas', 'Barra', 'Puxar', 'Intermediário'),
    createEx('remada-unilateral-halter', 'Remada Unilateral com Halter', 'Costas', 'Halteres', 'Puxar', 'Iniciante'),
    createEx('remada-baixa-cabo', 'Remada Baixa no Cabo', 'Costas', 'Cabo/Polia', 'Puxar', 'Iniciante'),
    createEx('remada-alta-cabo', 'Remada Alta no Cabo', 'Costas', 'Cabo/Polia', 'Puxar', 'Iniciante'),
    createEx('remada-cavalinho', 'Remada Cavalinho (T-bar)', 'Costas', 'Barra', 'Puxar', 'Intermediário'),
    createEx('remada-maq', 'Remada na Máquina', 'Costas', 'Máquina', 'Puxar', 'Iniciante'),
    createEx('pulldown-maq', 'Pulldown na Máquina', 'Costas', 'Máquina', 'Puxar', 'Intermediário'),
    createEx('pullover-cabo', 'Pullover no Cabo', 'Costas', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('pullover-halter-costas', 'Pullover com Halter', 'Costas', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('remada-banco-inc', 'Remada no Banco Inclinado', 'Costas', 'Halteres', 'Puxar', 'Intermediário'),
    createEx('remada-invertida', 'Remada Invertida', 'Costas', 'Peso do corpo', 'Puxar', 'Iniciante'),
    createEx('lev-terra', 'Levantamento Terra', 'Costas', 'Barra', 'Hinge', 'Avançado', ['Pernas', 'Lombar']),
    createEx('terra-romeno', 'Terra Romeno', 'Costas', 'Barra', 'Hinge', 'Avançado'),
    createEx('terra-sumo', 'Terra Sumô', 'Costas', 'Barra', 'Hinge', 'Avançado'),
    createEx('good-morning-costas', 'Good Morning', 'Costas', 'Barra', 'Hinge', 'Avançado'),
    createEx('hiperextensao-lombar', 'Hiperextensão Lombar', 'Costas', 'Máquina', 'Core', 'Iniciante'),
    createEx('face-pull-costas', 'Face Pull', 'Costas', 'Cabo/Polia', 'Puxar', 'Iniciante'),
    createEx('remada-alta-aberta', 'Remada Alta Aberta', 'Costas', 'Barra', 'Puxar', 'Intermediário'),
    createEx('remada-alta-fechada', 'Remada Alta Fechada', 'Costas', 'Barra', 'Puxar', 'Intermediário'),
    createEx('pulldown-uni', 'Pulldown Unilateral', 'Costas', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('barra-australiana', 'Barra Australiana', 'Costas', 'Peso do corpo', 'Puxar', 'Iniciante'),
    createEx('remada-baixa-pronada', 'Remada Baixa Pegada Pronada', 'Costas', 'Cabo/Polia', 'Puxar', 'Intermediário'),
    createEx('remada-baixa-supinada', 'Remada Baixa Pegada Supinada', 'Costas', 'Cabo/Polia', 'Puxar', 'Intermediário'),
    createEx('rack-pull', 'Rack Pull', 'Costas', 'Barra', 'Hinge', 'Avançado'),
    createEx('deadlift-parcial', 'Deadlift Parcial', 'Costas', 'Barra', 'Hinge', 'Avançado'),
  ],
  trapezio: [
    createEx('encolhe-barra', 'Encolhimento com Barra', 'Trapézio', 'Barra', 'Isolar', 'Iniciante'),
    createEx('encolhe-halter', 'Encolhimento com Halteres', 'Trapézio', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('encolhe-smith', 'Encolhimento no Smith', 'Trapézio', 'Smith', 'Isolar', 'Iniciante'),
    createEx('encolhe-cabo', 'Encolhimento no Cabo', 'Trapézio', 'Cabo/Polia', 'Isolar', 'Iniciante'),
    createEx('face-pull-trap', 'Face Pull', 'Trapézio', 'Cabo/Polia', 'Puxar', 'Iniciante'),
    createEx('high-pull', 'High Pull', 'Trapézio', 'Barra', 'Empurrar', 'Avançado'),
    createEx('rack-pull-trap', 'Rack Pull', 'Trapézio', 'Barra', 'Hinge', 'Avançado'),
    createEx('remada-alta-trap', 'Remada Alta com Barra', 'Trapézio', 'Barra', 'Puxar', 'Intermediário'),
    createEx('shrug-atras', 'Shrug atrás (Smith)', 'Trapézio', 'Smith', 'Isolar', 'Avançado'),
    createEx('shrug-uni', 'Shrug Unilateral', 'Trapézio', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('encolhe-banco-inc', 'Encolhimento no Banco Inclinado', 'Trapézio', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('farmers-walk-trap', 'Farmer’s Walk (Foco Trapézio)', 'Trapézio', 'Halteres', 'Empurrar', 'Intermediário'),
    createEx('encolhe-atras-halter', 'Encolhimento atrás com Halteres', 'Trapézio', 'Halteres', 'Isolar', 'Avançado'),
    createEx('encolhe-unilateral-cabo', 'Encolhimento Unilateral no Cabo', 'Trapézio', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('clean-shrug', 'Clean Shrug', 'Trapézio', 'Barra', 'Empurrar', 'Avançado'),
    createEx('encolhe-sentado', 'Encolhimento Sentado com Halteres', 'Trapézio', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('encolhe-anilhas', 'Encolhimento com Anilhas', 'Trapézio', 'Livre', 'Isolar', 'Iniciante'),
  ],
  lombar: [
    createEx('hiperextensao-v2', 'Hiperextensão Lombar', 'Lombar', 'Máquina', 'Core', 'Iniciante'),
    createEx('lev-terra-lombar', 'Levantamento Terra (Foco Lombar)', 'Lombar', 'Barra', 'Hinge', 'Avançado'),
    createEx('good-morning-lombar', 'Good Morning', 'Lombar', 'Barra', 'Hinge', 'Avançado'),
    createEx('superman', 'Superman', 'Lombar', 'Peso do corpo', 'Core', 'Iniciante'),
    createEx('bird-dog', 'Bird Dog', 'Lombar', 'Peso do corpo', 'Core', 'Iniciante'),
    createEx('reverse-hyper', 'Reverse Hyper', 'Lombar', 'Máquina', 'Hinge', 'Avançado'),
    createEx('deadlift-parcial-lombar', 'Deadlift Parcial', 'Lombar', 'Barra', 'Hinge', 'Avançado'),
    createEx('prancha-lombar', 'Prancha Lombar', 'Lombar', 'Peso do corpo', 'Core', 'Intermediário'),
    createEx('ponte-lombar', 'Ponte para Lombar', 'Lombar', 'Peso do corpo', 'Core', 'Iniciante'),
    createEx('stiff-lombar', 'Stiff (Foco Lombar)', 'Lombar', 'Barra', 'Hinge', 'Intermediário'),
  ],
  ombros: [
    createEx('desenv-barra', 'Desenvolvimento com Barra', 'Ombros', 'Barra', 'Empurrar', 'Intermediário', ['Tríceps']),
    createEx('desenv-halter', 'Desenvolvimento com Halteres', 'Ombros', 'Halteres', 'Empurrar', 'Iniciante'),
    createEx('desenv-maq', 'Desenvolvimento na Máquina', 'Ombros', 'Máquina', 'Empurrar', 'Iniciante'),
    createEx('arnold-press', 'Arnold Press', 'Ombros', 'Halteres', 'Empurrar', 'Avançado'),
    createEx('eleva-lateral-halter', 'Elevação Lateral com Halteres', 'Ombros', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('eleva-lateral-cabo', 'Elevação Lateral no Cabo', 'Ombros', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('eleva-lateral-maq', 'Elevação Lateral na Máquina', 'Ombros', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('eleva-frontal-barra', 'Elevação Frontal com Barra', 'Ombros', 'Barra', 'Isolar', 'Iniciante'),
    createEx('eleva-frontal-halter', 'Elevação Frontal com Halteres', 'Ombros', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('eleva-frontal-cabo', 'Elevação Frontal no Cabo', 'Ombros', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('eleva-frontal-alt', 'Elevação Frontal Alternada', 'Ombros', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('remada-alta-ombro', 'Remada Alta com Barra', 'Ombros', 'Barra', 'Puxar', 'Intermediário'),
    createEx('remada-alta-cabo-ombro', 'Remada Alta no Cabo', 'Ombros', 'Cabo/Polia', 'Puxar', 'Intermediário'),
    createEx('eleva-post-peck', 'Elevação Posterior no Peck Deck', 'Ombros', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('eleva-post-halter', 'Elevação Posterior com Halteres', 'Ombros', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('face-pull-ombro', 'Face Pull', 'Ombros', 'Cabo/Polia', 'Puxar', 'Iniciante'),
    createEx('press-militar', 'Press Militar', 'Ombros', 'Barra', 'Empurrar', 'Avançado'),
    createEx('press-unilateral', 'Press Unilateral', 'Ombros', 'Halteres', 'Empurrar', 'Intermediário'),
    createEx('eleva-lat-inc', 'Elevação Lateral Inclinada', 'Ombros', 'Halteres', 'Isolar', 'Avançado'),
    createEx('eleva-lat-sent', 'Elevação Lateral Sentada', 'Ombros', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('eleva-lat-uni-cabo', 'Elevação Lateral Unilateral no Cabo', 'Ombros', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('eleva-front-anilha', 'Elevação Frontal com Anilha', 'Ombros', 'Livre', 'Isolar', 'Iniciante'),
    createEx('y-raise', 'Y-raise', 'Ombros', 'Halteres', 'Isolar', 'Avançado'),
  ],
  biceps: [
    createEx('rosca-direta-barra', 'Rosca Direta com Barra', 'Bíceps', 'Barra', 'Isolar', 'Iniciante'),
    createEx('rosca-direta-halter', 'Rosca Direta com Halteres', 'Bíceps', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('rosca-alternada', 'Rosca Alternada', 'Bíceps', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('rosca-martelo', 'Rosca Martelo', 'Bíceps', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('rosca-martelo-cruzada', 'Rosca Martelo Cruzada', 'Bíceps', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('rosca-concentrada', 'Rosca Concentrada', 'Bíceps', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('rosca-scott-barra', 'Rosca Scott com Barra', 'Bíceps', 'Barra', 'Isolar', 'Intermediário'),
    createEx('rosca-scott-maq', 'Rosca Scott na Máquina', 'Bíceps', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('rosca-cabo', 'Rosca no Cabo', 'Bíceps', 'Cabo/Polia', 'Isolar', 'Iniciante'),
    createEx('rosca-21', 'Rosca 21', 'Bíceps', 'Barra', 'Isolar', 'Avançado'),
    createEx('rosca-inversa', 'Rosca Inversa', 'Bíceps', 'Barra', 'Isolar', 'Intermediário', ['Antebraço']),
    createEx('rosca-banco-inc', 'Rosca no Banco Inclinado', 'Bíceps', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('rosca-spider', 'Rosca Spider', 'Bíceps', 'Barra', 'Isolar', 'Avançado'),
    createEx('rosca-uni-cabo', 'Rosca Unilateral no Cabo', 'Bíceps', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('rosca-barra-w', 'Rosca com Barra W', 'Bíceps', 'Barra', 'Isolar', 'Iniciante'),
    createEx('rosca-isometrica', 'Rosca Isométrica', 'Bíceps', 'Halteres', 'Isolar', 'Avançado'),
    createEx('chin-up', 'Chin-up (Barra Fixa Supinada)', 'Bíceps', 'Peso do corpo', 'Puxar', 'Intermediário'),
    createEx('rosca-45-graus', 'Rosca em 45 graus', 'Bíceps', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('rosca-neutra', 'Rosca com Pegada Neutra', 'Bíceps', 'Halteres', 'Isolar', 'Iniciante'),
  ],
  triceps: [
    createEx('triceps-testa-barra', 'Tríceps Testa com Barra', 'Tríceps', 'Barra', 'Isolar', 'Intermediário'),
    createEx('triceps-testa-halter', 'Tríceps Testa com Halteres', 'Tríceps', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('triceps-corda', 'Tríceps Corda', 'Tríceps', 'Cabo/Polia', 'Isolar', 'Iniciante'),
    createEx('triceps-pulley', 'Tríceps no Pulley', 'Tríceps', 'Cabo/Polia', 'Isolar', 'Iniciante'),
    createEx('triceps-frances', 'Tríceps Francês', 'Tríceps', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('triceps-frances-uni', 'Tríceps Francês Unilateral', 'Tríceps', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('mergulho-paralelas', 'Mergulho em Paralelas', 'Tríceps', 'Peso do corpo', 'Empurrar', 'Avançado'),
    createEx('mergulho-banco', 'Mergulho em Banco', 'Tríceps', 'Peso do corpo', 'Empurrar', 'Iniciante'),
    createEx('triceps-coice', 'Tríceps Coice', 'Tríceps', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('supino-fechado', 'Supino Fechado', 'Tríceps', 'Barra', 'Empurrar', 'Intermediário'),
    createEx('ext-acima-halter', 'Extensão acima da cabeça com halter', 'Tríceps', 'Halteres', 'Isolar', 'Intermediário'),
    createEx('ext-acima-cabo', 'Extensão acima da cabeça no cabo', 'Tríceps', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('triceps-maq', 'Tríceps Máquina', 'Tríceps', 'Máquina', 'Empurrar', 'Iniciante'),
    createEx('triceps-barra-v', 'Tríceps com Barra V', 'Tríceps', 'Cabo/Polia', 'Isolar', 'Iniciante'),
    createEx('triceps-reversa', 'Tríceps com Pegada Reversa', 'Tríceps', 'Cabo/Polia', 'Isolar', 'Intermediário'),
  ],
  pernas: [
    createEx('agachamento-livre', 'Agachamento Livre', 'Pernas', 'Barra', 'Agachar', 'Avançado', ['Glúteos']),
    createEx('agachamento-frontal', 'Agachamento Frontal', 'Pernas', 'Barra', 'Agachar', 'Avançado'),
    createEx('agachamento-sumo', 'Agachamento Sumô', 'Pernas', 'Barra', 'Agachar', 'Intermediário'),
    createEx('agachamento-bulgaro', 'Agachamento Búlgaro', 'Pernas', 'Halteres', 'Agachar', 'Avançado'),
    createEx('leg-press-45', 'Leg Press 45°', 'Pernas', 'Máquina', 'Empurrar', 'Intermediário'),
    createEx('leg-press-horiz', 'Leg Press Horizontal', 'Pernas', 'Máquina', 'Empurrar', 'Iniciante'),
    createEx('cadeira-extensora', 'Cadeira Extensora', 'Pernas', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('hack-machine', 'Hack Machine', 'Pernas', 'Máquina', 'Agachar', 'Intermediário'),
    createEx('afundo', 'Afundo', 'Pernas', 'Halteres', 'Agachar', 'Iniciante'),
    createEx('stiff', 'Stiff', 'Pernas', 'Barra', 'Hinge', 'Intermediário'),
    createEx('terra-romeno-perna', 'Terra Romeno', 'Pernas', 'Barra', 'Hinge', 'Avançado'),
    createEx('mesa-flexora', 'Mesa Flexora', 'Pernas', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('cadeira-flexora', 'Cadeira Flexora', 'Pernas', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('hip-thrust', 'Hip Thrust (Elevação Pélvica)', 'Pernas', 'Barra', 'Hinge', 'Intermediário', ['Glúteos']),
    createEx('abducao-quadril-maq', 'Abdução de Quadril Máquina', 'Pernas', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('aducao-quadril-maq', 'Adução de Quadril Máquina', 'Pernas', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('pistol-squat', 'Pistol Squat', 'Pernas', 'Peso do corpo', 'Agachar', 'Avançado'),
    createEx('swing-kettlebell', 'Swing com Kettlebell', 'Pernas', 'Kettlebell', 'Hinge', 'Intermediário'),
    createEx('cadeira-abdutora', 'Cadeira Abdutora', 'Pernas', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('cadeira-adutora', 'Cadeira Adutora', 'Pernas', 'Máquina', 'Isolar', 'Iniciante'),
  ],
  panturrilha: [
    createEx('eleva-pe', 'Elevação em Pé', 'Panturrilha', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('eleva-sentado', 'Elevação Sentado', 'Panturrilha', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('panturrilha-leg', 'Panturrilha no Leg Press', 'Panturrilha', 'Máquina', 'Isolar', 'Iniciante'),
    createEx('panturrilha-uni', 'Panturrilha Unilateral', 'Panturrilha', 'Peso do corpo', 'Isolar', 'Iniciante'),
    createEx('panturrilha-halter', 'Panturrilha com Halter', 'Panturrilha', 'Halteres', 'Isolar', 'Iniciante'),
    createEx('panturrilha-cabo', 'Panturrilha no Cabo', 'Panturrilha', 'Cabo/Polia', 'Isolar', 'Intermediário'),
  ],
  abdomen: [
    createEx('crunch', 'Abdominal Crunch', 'Abdômen', 'Peso do corpo', 'Core', 'Iniciante'),
    createEx('abd-maq', 'Abdominal Máquina', 'Abdômen', 'Máquina', 'Core', 'Iniciante'),
    createEx('abd-cabo', 'Abdominal no Cabo', 'Abdômen', 'Cabo/Polia', 'Core', 'Iniciante'),
    createEx('elev-pernas-barra', 'Elevação de Pernas na Barra', 'Abdômen', 'Peso do corpo', 'Core', 'Avançado'),
    createEx('prancha', 'Prancha Isométrica', 'Abdômen', 'Peso do corpo', 'Core', 'Iniciante'),
    createEx('ab-wheel', 'Ab Wheel (Roda)', 'Abdômen', 'Livre', 'Core', 'Avançado'),
    createEx('russian-twist', 'Russian Twist', 'Abdômen', 'Livre', 'Core', 'Intermediário'),
    createEx('mountain-climber', 'Mountain Climber', 'Abdômen', 'Peso do corpo', 'Core', 'Intermediário'),
    createEx('woodchopper', 'Woodchopper no Cabo', 'Abdômen', 'Cabo/Polia', 'Core', 'Intermediário'),
    createEx('prancha-din', 'Prancha dinâmica', 'Abdômen', 'Peso do corpo', 'Core', 'Intermediário'),
  ],
  antebreaco: [
    createEx('rosca-inversa-ante', 'Rosca Inversa', 'Antebraço', 'Barra', 'Isolar', 'Iniciante'),
    createEx('rosca-punho', 'Rosca Punho', 'Antebraço', 'Barra', 'Isolar', 'Iniciante'),
    createEx('rosca-punho-rev', 'Rosca Punho Reversa', 'Antebraço', 'Barra', 'Isolar', 'Iniciante'),
    createEx('farmer-walk', 'Farmer’s Walk', 'Antebraço', 'Halteres', 'Empurrar', 'Intermediário'),
    createEx('wrist-roller', 'Wrist Roller', 'Antebraço', 'Livre', 'Isolar', 'Intermediário'),
    createEx('flex-punho-cabo', 'Flexão de punho no cabo', 'Antebraço', 'Cabo/Polia', 'Isolar', 'Intermediário'),
    createEx('ext-punho-cabo', 'Extensão de punho no cabo', 'Antebraço', 'Cabo/Polia', 'Isolar', 'Intermediário'),
  ],
};

export { placeHolderImages } from './placeholder-images';
